### ISSUE TITLE
The management file of the NAT46 interfaces scope is not avaible in docker container

### ISSUE THREAD

**Issue by shubham9418** [ayourtch/nat46#17]
Hi,

I am using nat46 kernel module with kernel version-5.4.91.

I have a use-case where nat46 translations will be done on Docker Container. ( Privileged container having full access to kernel).
But management file of the NAT46 is missing in docker container.
Loading and unloading of nat46.ko doesnt make any effect.

**Setup : HostOS and docker container are running on OpenWrt.**

root@OpenWrt:/etc# lsmod | grep nat46
nat46                  36864  0
root@OpenWrt:/etc#
root@OpenWrt:/etc# ls -lrt /proc/net/nat46
ls: /proc/net/nat46: No such file or directory
root@OpenWrt:/etc#

PS: I can see and control /proc/net/nat46/control on host OS. But thats not the use case.

**Comment by ayourtch** [comment]
nat46 does not have any knowledge about docker.You will need to investigate how to configure the docker container such that it could see the /proc/net/nat46 interface.
