### ISSUE TITLE
RFC6052 style type doesn't consider v4 prefix

### ISSUE THREAD

**Issue by detobate** [ayourtch/nat46#6]
With ruleset:

```
add map-wan6_4
insert map-wan6_4 local.v4 0.0.0.0/0 local.v6 ::/0 local.style NONE local.ea-len 0 local.psid-offset 0 remote.v4 90.223.190.192/28 remote.v6 2a02:c7a:8000:fe07::/64 remote.style RFC6052 remote.ea-len 0 remote.psid-offset 0 debug 0
insert map-wan6_4 local.v4 0.0.0.0/0 local.v6 ::/0 local.style NONE local.ea-len 0 local.psid-offset 0 remote.v4 2.127.254.0/28 remote.v6 2a02:c7a:fe40::/48 remote.style MAP remote.ea-len 8 remote.psid-offset 6 debug 0
config map-wan6_4 local.v4 2.127.254.0/28 local.v6 2a02:c7a:fe40::/48 local.style MAP local.ea-len 8 local.psid-offset 6 remote.v4 0.0.0.0/0 remote.v6 2a02:c7a:fdff::/64 remote.style RFC6052 remote.ea-len 0 remote.psid-offset 0 debug 0
```

All v4 packets are incorrectly translated using the top-most rule, to 2a02:c7a:8000:fe07::/64 instead of following the BMR and being translated to 2a02:c7a:fdff::/64

Expected behaviour is that only packets destined to the v4 prefix 90.223.190.192/28 get translated to 2a02:c7a:8000:fe07::/64, all other IPv4 destinations should be translated to 2a02:c7a:fdff::/64

**Comment by detobate** [comment]
The rule matching check in pairs_xlate_v4_to_v6_outer() checks to see if both the SRC and DST can be mapped successfully by xlate_v4_to_v6().  
Because rules with remote.style RFC6052 will always succeed, only the first rule in the list is ever evaluated.

https://goo.gl/8gsiZL and https://goo.gl/yHdm1D

**Comment by ayourtch** [comment]
Try configuring local map rule with the same parameters and FMR flag set - browsing the code, this might help.

Looking at it, potentially in general configuring the remote rule as MAP with the appropriate parameters might work...

Else of course I am happy to merge a pull request to add the check for RFC6052 type, or I might be able look at it in myself in a couple of weeks or so... - busy on VPP coding atm :)

**Comment by detobate** [comment]
> Try configuring local map rule with the same parameters and FMR flag set - browsing the code, this might help.

Think I've tried all sorts of combinations, including that, but will try it again.

> Looking at it, potentially in general configuring the remote rule as MAP with the appropriate parameters might work...

This is how OpenWRT currently installs the rules, which results in incorrect translation (because it's not following RFC6052).   I've raised [this bug](https://bugs.openwrt.org/index.php?do=details&task_id=1430) over there.

> Else of course I am happy to merge a pull request to add the check for RFC6052 type, or I might be able look at it in myself in a couple of weeks or so... - busy on VPP coding atm :)

I'll give it a shot, but I'll need to setup a dev environment and give it a proper test before I submit the PR.  :)

**Comment by detobate** [comment]
After re-reading the RFC, I think I was mistaken thinking that an FMR could use the RFC6052 style address mapping.
